### ISSUE TITLE
Ppsapp patch for M16S_A2_V10_F37 / v 4.0.6

### ISSUE THREAD

**Issue by roaringbits** [guino/ppsapp-rtsp#20]
Could you please help me patch M16S_A2_V10_F37 / v 4.0.6 as well? :-)

{
	"devname": "Smart Home Camera",
	"model": "Mini 16S",
	"serialno": "100134974",
	"softwareversion": "4.0.6",
	"hardwareversion": "M16S_A2_V10_F37",
	"firmwareversion": "ppstrong-a3-tuya2_lsc-4.0.6.20210311",
	"identity": "M1K006CF3B02018399",
	"authkey": "RMQP8t2U4JCUlPAsR3awa4Q2lTyPMV8F",
	"deviceid": "pp01efa84ca8a602ee9a",
	"pid": "aaa",
	"WiFi MAC": "b4:fb:e3:a4:e3:f7",
	"ETH MAC": "00:00:00:00:00:00"
}

--deleted--

**Comment by roaringbits** [comment]
Could you please help me patch M16S_A2_V10_F37 / v 4.0.6 as well? :-)

{
	"devname": "Smart Home Camera",
	"model": "Mini 16S",
	"serialno": "100134974",
	"softwareversion": "4.0.6",
	"hardwareversion": "M16S_A2_V10_F37",
	"firmwareversion": "ppstrong-a3-tuya2_lsc-4.0.6.20210311",
	"identity": "M1K006CF3B02018399",
	"authkey": "RMQP8t2U4JCUlPAsR3awa4Q2lTyPMV8F",
	"deviceid": "pp01efa84ca8a602ee9a",
	"pid": "aaa",
	"WiFi MAC": "b4:fb:e3:a4:e3:f7",
	"ETH MAC": "00:00:00:00:00:00"
}

[ppsapp.zip](https://github.com/guino/ppsapp-rtsp/files/7013976/ppsapp.zip)

**Comment by roaringbits** [comment]
Sorry, missed the patch you've already provided for this firmware.

**Comment by djgerry300** [comment]
Confirmed: the patch in issue [#1](https://github.com/guino/ppsapp-rtsp/issues/1)'s table for M16S_A2_V10_F37 / ppstrong-a3-tuya2_lsc-4.0.6.20210311 (MD5 363543651299a6178a4ba77727cc39b5) works and is stable. Installed it directly into the app partition instead of via SD card. Wrote up the flash-write method in [BazzDoorbell#4](https://github.com/guino/BazzDoorbell/issues/4#issuecomment-5402036187) for anyone else without flash tools.
